Nexters/Bottles_iOS

Projects/Core/Network/Interface/Sources/API/AnyAPIType.swift, Projects/Core/Network/Interface/Sources/API/BaseTargetType.swift, Projects/Core/Network/Interface/Sources/NetworkInterface.swift, Projects/Core/Network/Interface/Sources/NetworkManager/NetworkManagable.swift, Projects/Core/Network/Interface/Sources/Provider/Providable.swift, Projects/Core/Network/Project.swift, Projects/Core/Network/Sources/NetworkManager/NetworkManager.swift, Projects/Core/Network/Sources/Provider/Provider.swift, Projects/Core/Network/Sources/Source.swift
이슈 #4 
- Moya Provider 네트워크 요청 async/await로 래핑
- Domain 모듈에서 API 정의할 수 있도록 BaseTargetType 구현
- NetworkManager 구현 (네트워크 요청 및 디코딩)
TCA의 Dependency를 통해서 의존성을 관리하다보니 실질적으로 DIP를 통해 의존성 주입이 이뤄지지 않아서 NetworkManager 구현부에 살짝 어색한 부분이 있는데 이 부분에 대해서 얘기해보면 좋을 거 같슴다 
Domain 쪽에서 사용할 때 아래처럼 사용해주시면 됩니다
``` swift
// HomeFeature Interface
enum HomeAPI {
case fetchBottles
}
enum HomeAPI: BaseTargetType {
var path: String {
switch self {
case .fetchBottles:
return "/v1/bottles"
}
}
var method: Moya.Method {
switch self {
case .fetchBottles:
return .get
}
}
var task: Moya.Task {
switch self {
case .fetchBottles:
return .requestPlain
}
}
}
```
``` swift
// HomeFeature Impelements
public struct HomeClient {
@Dependency(\.network) var network
public func someMethod() async throws {
try await network.reqeust(api: …
```
=> [Feature/#4] 네트워크 모듈 구현

Projects/Core/Util/Sources/Modifiers/AsButtonModifier.swift, Projects/Core/Util/Sources/Modifiers/AsDebounceButtonModifier.swift, Projects/Core/Util/Sources/Modifiers/AsThrottleButtonModifier.swift
- 일반 버튼, 스로틀 버튼, 디바운스 버튼 생성 모디 파이어 추가
- 아직 내부 로직은 구현안헀는데 상황에 맞게 일단 적용해놓고 내부 로직은 출히하고 구현하자
- TCA에도 debounce가 있지만 내가 알기로는 비동기 로직 실행하는 메소드 사용할 때만 적용이 가능해서 모디 파이어들 따로 구현해서 run 메소드 사용하지 않는 상황에도 활용해보고 싶어서 추가했어!
- [TCA debounce 문서](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/effect/debounce(id:for:scheduler:options:))
=> [Feature/#28] 버튼 생성 모디파이어들 추가

Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/ClipListTest/ClipListContainerViewTest.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/ClipListTest/ClipListViewTest.swift, Projects/Shared/DesignSystem/Sources/Components/Card/ChipListLayout.swift, Projects/Shared/DesignSystem/Sources/Components/Card/ClipItem.swift, Projects/Shared/DesignSystem/Sources/Components/Card/ClipListContainerView.swift, Projects/Shared/DesignSystem/Sources/Components/Card/ClipListView.swift
이슈 #55 
https://github.com/user-attachments/assets/80fdec93-3bf1-4d19-8dd0-64a3b3610c45
- ClipListView 구현
- ClipListContainerView 구현
- ClipItem 구현
- ClipListLayout 구현
- Layout 프로토콜 채택한 ClipListLayout 구현해서 부모 뷰의 최대 너비와 배치했을 때 x 좌표 위치 고려하면서 아래로 position 조정하면서 구현하는 방식으로 했어!
- 지금은 ClipList 쓰는 GUI들 3개 Section으로 고정되어있는데 확장성 고려해서 ClipItem 배열받아서 그리도록 함!
- 나중에 보틀 보관함 구현할 때 ClipListContainerView 사용하면 될 듯!
=> [Feature/#55] ClipList DesignSystem 구현

Projects/Core/Network/Interface/Sources/API/BaseTargetType.swift, Projects/Core/Network/Interface/Sources/NetworkManager/NetworkManagable.swift, Projects/Core/Network/Interface/Sources/Provider/Providable.swift, Projects/Core/Network/Sources/Interceptor/Refresh/RefreshAPI.swift, Projects/Core/Network/Sources/Interceptor/Refresh/RefreshResponseDTO.swift, Projects/Core/Network/Sources/Interceptor/TokenInterceptor.swift, Projects/Core/Network/Sources/NetworkManager/NetworkManager.swift, Projects/Core/Network/Sources/Provider/Provider.swift, Projects/Domain/Auth/Interface/Sources/DTO/Response/SignInResponseDTO.swift, Projects/Feature/Login/Example/Sources/AppView.swift, Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift, Projects/Feature/Login/Interface/Sources/Login/LoginView.swift, Projects/Feature/Login/Sources/Login/LoginFeature.swift, Projects/Feature/Sources/App/AppFeature.swift
이슈 #52 
https://github.com/user-attachments/assets/8db65d24-92be-4b05-9e3a-170cb3dacfaa
로그인 Feature쪽 구현하려고하자는 이슈였지만 본의아니게 Network쪽이랑 Domain쪽도 많이 손봐버림..
- TokenInterceptor 구현 (NSLock, 토큰 검증 로직 추가)
- 로그인 상태에 따른 초기 화면 처리
- 카카오 로그인 버튼 클릭 시 카카오톡 or 카카오 웹으로 로그인 처리 후 앱 복귀 구현
아직 화면 전환쪽은 손안대놨고 LoginFeature 구현부쪽에 Todo로 남겨놨음!
그리고 카카오 로그인 버튼 작업하는거는 추가적으로 이슈파서 작업할게!
=> [Feature/#52] Login Feature 구현

Projects/Feature/BottleStorage/Example/Sources/AppView.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift, Projects/Feature/SandBeach/Example/Sources/AppView.swift, Projects/Shared/DesignSystem/Sources/Extension/PreferenceKey/CGSizePreferenceKey.swift, Projects/Shared/DesignSystem/Sources/Extension/View+Extensions.swift
- 보틀 보관함 상세 탭뷰 구현
- TabView로 깜싸면 내부 View의 크기에 맞게 늘어나지 않아 동적으로 높이 조절하기어려움, view+ extension에 view의 size를알 수 있는 메소드 만들었는데 이걸 사용해도 잘안됨 [참고 브랜치](https://github.com/Nexters/Bottles_iOS/tree/%ED%83%AD%EB%B7%B0-%EB%AC%B8%EC%A0%9C)
=> [feature/#102] 보틀 보관함 상세 탭뷰 구현

Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift, Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift, Projects/Feature/Sources/TabView/MainTabViewFeature.swift, Projects/Feature/TabBar/Interface/Sources/TabBarModifier.swift
이슈 #145 
- 자기소개 작성 후 마이페이지 유저 데이터 업데이트 구현
=> [Feature/#145] 자기소개 작성 후 마이페이지 유저 데이터 업데이트 구현

Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift, Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift, Projects/Feature/Sources/TabView/MainTabView.swift
이슈 #148 
- UITabBarController TabBar hidden 처리
- UITabBarController의 TabBar를 hidden처리해서 우선적으로 탭 이동시 보이던 UITabBar는 안보이게 설정했음 (도대체 왜 보이는 건지 모르겠다..)
- 안보이고 동작을 안해도 탭바가 차지하고 있는 영역은 그대로 이기 때문에 bottom ignoreSafeArea처리해서 사용해야하는 번거로움이 있음
- 추후에 View를 감싸는 BaseView를 통해 기본 Modifier들을 처리하면 될 것 같음!
=> [Feature/#148] UITabBarController TabBar hidden 처리

Projects/Domain/Profile/Interface/Sources/API/ProfileAPI.swift, Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileStatusResponseDTO.swift, Projects/Domain/Profile/Interface/Sources/Entity/UserProfileStatus.swift, Projects/Domain/Profile/Interface/Sources/ProfileClient.swift, Projects/Domain/Profile/Sources/ProfileClient.swift, Projects/Feature/Sources/App/AppFeature.swift, Projects/Feature/Sources/App/AppView.swift
이슈 #153 
https://github.com/user-attachments/assets/864bb038-45d3-4a1a-9aaf-d4a545c56650
- UserStatus fetch API 추가
- 프로필 작성 여부 확인 후 상황에 맞는 View 처리
현재 Client의 역할이 다분화되어있음
1. entity를 그대로 feature 레이어에 전달
2. entity를 통해 비즈니스 로직을 수행 한뒤 결과값을 전달.
1의 경우에는 feature에서 비즈니스 로직을 수행하기 때문에 client 내부 메소드가 여러 feature에서 재사용이 가능하다는 장점이 있지만
2의 경우에는 같은 API라도 내부에서 처리하는 로직이 다른 경우 client 내부에서 여러 메소드를 둬서 동일한 API를 호출하고 있음.
통일되지 않은 client의 역할을 확실하게 잡고가야 추후에 유지보수 시 좀 더 명확하게 작업을 할 수 있을 거 같음
1. data layer를 새로 만들어서 현재 domain 레이어에 있는 client에서 비즈니스 로직 처리
2. client는 entity를 feature 레이어에 전달하는 역할만 가지고 비즈니스 로직은 feature에서 처리.
=> [Feature/#153] 프로필 설정 중 앱 종료 시 대응

Projects/Feature/BottleStorage/Example/Sources/AppView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
- 이슈: #199 
https://github.com/user-attachments/assets/41e48017-a843-4613-95b5-1ab5ae45a9ad
- 핑퐁 문답 섹션 pull to refresh 구현
=> [Feature/#199] 핑퐁 문답 화면 pull to refresh 구현

Projects/App/Sources/AppDelegate.swift, Projects/Domain/Auth/Sources/AuthClient.swift, Projects/Domain/User/Interface/Sources/UserClient.swift, Projects/Domain/User/Sources/UserClient.swift, Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift, Projects/Feature/Login/Interface/Sources/Login/LoginView.swift, Projects/Feature/Sources/App/AppDelegateFeature.swift, Projects/Feature/Sources/App/AppFeature.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
=> v1.0.3 Release -> Develop

Projects/Shared/DesignSystem/Sources/Extension/UIImage+Extensions.swift
이슈 #220 
- 이미지 다운 샘플링 resizeScale 수정
시뮬레이터 내장 이미지 중 가장 큰 데이터로 테스트했었을 때는 문제가 없었지만 해당 이미지들보다 더 큰 이미지를 사용자가 선택했을 때
resizeScale이 0.75로 고정되어있다보니 targetSize로 압축하지 못해 무한 루프를 도는 현상이 발생했음
반복문을 돌때마다 0.75배씩 줄어들게 해서 이미지가 반복적으로 작아지게 해 targetSize보다 작아지도록 수정함.
테스트코드 빨리 작성해야될 듯!!
=> [Feature#220] 이미지 다운 샘플링 reszieScale 수정

Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
이슈 #223 
- ProfileImageUploadView WithPerceptionTracking 추가
- 전달받은 캐릭터 이미지를 통해서 1.0.5 release버전으로 테스트를 해본 결과 문제 없이 작동함.
- 제보받은 디바이스의 화면을 확인해봤을 때 이미지 선택 후 imagePickerButton에 선택된 이미지가 보여지는 것을 봐서는 이미지 선택하는 로직쪽에는 문제가 없는 것 같음
``` swift
private extension ProfileImageUploadView {
func handleSelectedPhotos(_ newPhotos: [PhotosPickerItem]) {
for newPhoto in newPhotos {
newPhoto.loadTransferable(type: Data.self) { result in
switch result {
case .success(let data):
if let data = data, let newImage = UIImage(data: data) {
DispatchQueue.main.async {
selectedImage = [newImage] // 빈 값
let compressData = newImage.compressImageData() // nil로 처리
store.send(.imageDidSelected(selectedImageData: compressData ?? .init()))
}
}
// TODO: 이미지 로드 실패 처리
case .failure(_):
return
}
}
}
selectedItems.removeAll()
}
} …
```
=> [fix#223] 이미지 선택 시 버튼 활성화되지 않는 버그

Projects/Domain/User/Interface/Sources/API/UserAPI.swift, Projects/Domain/User/Interface/Sources/DTO/Request/AlertStateRequestDTO.swift, Projects/Domain/User/Interface/Sources/DTO/Response/AlertStateReponseDTO.swift, Projects/Domain/User/Interface/Sources/Entity/AlertState.swift, Projects/Domain/User/Interface/Sources/Entity/AlertType.swift, Projects/Domain/User/Interface/Sources/UserClient.swift, Projects/Domain/User/Sources/UserClient.swift, Projects/Feature/MyPage/Interface/Sources/AlertSetting/AlertSettingFeature.swift, Projects/Feature/MyPage/Interface/Sources/AlertSetting/AlertSettingFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/AlertSetting/AlertSettingView.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift, Projects/Feature/Sources/TabView/MainTabView.swift, Projects/Feature/Sources/TabView/MainTabViewFeature.swift
이슈 #252 
https://github.com/user-attachments/assets/1acabc57-d21a-4125-8039-c54fecf419c4
- MyPageRoot 구현
- 알림설정 화면 및 기능 구현
- 화면 전환 담당하는 MyPageRootView, MyPageRootFeature, MyPageRootFeatureInterface 구현해뒀어!
아마 형 작업하는거랑 합치게되면 컨플릭 엄청날거같음..ㅋㅋ
- Toggle 디바운스 1초로 해뒀는데 의견있음 말해줘!
=> [Feature/#252] 마이페이지 알림설정 구현

Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
이슈 #268 
- 연락처 차단 완료 시 Toast 띄우기
- 연락처 차단 업데이트 클릭 시 Alert 추가
=> [Feature/#268] 연락처 차단 완료 시 Toast 띄우기

Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
> issue: #277 
- 웹뷰에 os type, 앱 버전 전달하는 로직 추가
=> [Feature/#277] 웹뷰 os type, 버전 파라미터 추가

Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
> 이슈: #280 
- 로그인 화면 백그라운드 이미지 수정
> 왼쪽 변경 전, 오른쪽 변경 후
=> [Fix/#280] 로그인화면 백그라운드 이미지 비율 수정

Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift, Projects/Feature/Report/Interface/Sources/ReportUserFeature.swift, Projects/Feature/Report/Interface/Sources/ReportUserFeatureInterface.swift, Projects/Feature/Report/Interface/Sources/ReportUserView.swift, Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachView.swift, Projects/Feature/Sources/SplashView/SplashView.swift
이슈 #232 
- SplashView bottleAlert 적용
- PingPongDetailView bottleAlert 적용
- ReportUserView bottleAlert 적용
- SandBeachView bottleAlert 적용
- 기존에 PingPongDetailView는 tabButtons의 상태에 따라 IntroductionView, QuestionAndAnswerView, MatchingView를 보여주고 있었음
- IntroductionView, QuestionAndAnswerView은 각각 AlertState와 destination을 가지고 Alert를 띄워주고 있음
- 현재 bottleAlert Modifier는 ZStack으로 현재 View에 Custom Alert를 띄우는 방식이다보니 전체 화면에 Alert가 띄워지는게 아니라 IntroductionView, QuestionAndAnswerView에 Alert가 띄워짐 -> 위의 이미지처럼 됨
- 따라서, PingPongDetailView에서 Alert를 띄우는 거로 변경해서 해결
=> [Feature/#232] 커스텀 alert 적용

Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingFeature.swift
이슈 #273 
- 탈퇴하기 alert message 수정
=> [Feature/#273] 탈퇴하기 alert message 수정

Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift
> 이슈: #310 
- 마이페이지 중복된 setTabBar 모디파이어 제거
=> [refactor/#310] 마이페이지 중복된 setTabBar 모디파이어 제거

Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift
> 이슈: #314 
- 보틀 보관함 하단에 탭 높이만큼 패딩 값 추가 필요
- 변경 전
https://github.com/user-attachments/assets/b7deea0d-e443-44d3-b073-ec6e988cc89a
- 변경 후
https://github.com/user-attachments/assets/79abb021-9f18-4c49-953d-4055701d915a
=> [Fix/#314] 보틀 보관함 하단에 탭 높이만큼 패딩값 추가 필요

Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift, Projects/Shared/DesignSystem/Sources/Components/Button/SegmentControlButton/SegmentControlButton.swift, Projects/Shared/DesignSystem/Sources/Components/Button/SegmentControlButton/SegmentControlButtonStyle.swift
이슈 #294 
https://github.com/user-attachments/assets/6ae48343-397a-41a8-984b-3f3d85095cac
- 문답 화면 SegmentedControl 버튼 구현 및 적용
- SegmentControl 자체를 DesignSystem으로 빼려다가 그냥 Button만 디자인 요구사항에 맞게 적용하는게 구조상 더 간편해보여서 Button만 OutlinedButton에서 SegmentControlButton으로 바꿈!
=> [Feature/#294] 문답화면 segmented control 디자인 수정
