Nexters/Bottles_iOS

Makefile
- make genrate 명령어 수정
- 외부 의존성 제외하고 그래프 그리는 명령어 추가
=> [Setting/#7] tuist makefile 명령어 수정 및 추가

Projects/Core/Logger/Interface/Sources/Log.swift, Projects/Core/Logger/Interface/Sources/LoggerInterface.swift, Projects/Core/Logger/Interface/Sources/OSLog+Extensions.swift, Projects/Core/Network/Project.swift, Projects/Core/Network/Sources/MoyaPulgins/MoyaLoggerPlugin.swift, Projects/Core/Network/Sources/Provider/Provider.swift
이슈 #5 
- OSLog를 통해 Log 구현
- Moya PluginType을 통해 Network 통신 로깅 구현
=> [Feature/#5] Log 모듈 구현

Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
- app 모듈의 info plist에 UILaunchScreen 값 추가해 여백 생기지 않도록 수정
=> [Setting/#9] view가 screen에 표시될 때 상하단 여백 생기는 현상 수정

Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
- uiuserinterfacestyle: 라이트 모드 고정
- UI supported interface orientations: portrait 모드 고정
=> [Setting/#30] uiuserinterfacestyle,UI supported interface orientations 세팅

Projects/Feature/Sources/TabView/MainTabView.swift, Projects/Feature/Sources/TabView/TabType.swift
=> [Setting/#3] TabType 코드 파일 생성해 분리

Projects/Shared/DesignSystem/Sources/Token/ColorToken+Background.swift, Projects/Shared/DesignSystem/Sources/Token/ColorToken+Border.swift
=> [feature#14] SwfitUI import 누락 수정

Projects/Shared/DesignSystem/Sources/Spacing/HStack+Spacing.swift, Projects/Shared/DesignSystem/Sources/Spacing/Spacable.swift, Projects/Shared/DesignSystem/Sources/Spacing/Spacer+Extensions.swift, Projects/Shared/DesignSystem/Sources/Spacing/VStack+Spacing.swift
이슈 #15 
- BottleSpacingType 구현
- BottleSpacingType을 통한 Spacer 생성자 구현
- BottleSpacingType을 통한 HStack 생성자 구현 
- BottleSpacingType을 통한 VStack 생성자 구현
=> [Feature/#22] Spacing DesignSystem 구현

Projects/Shared/DesignSystem/Sources/Padding/BottlePaddingType.swift, Projects/Shared/DesignSystem/Sources/Padding/View+Padding.swift
이슈 #36 
- BottlePaddingType 구현
- BottlePaddingType을 통한 padding 메소드 래핑
=> [Feature/#36] Padding DesignSystem 구현

Projects/Shared/DesignSystem/Sources/Radius/BottleRadiusType.swift
=> [feature/#37] Radius DesignSystem 구현

Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/LinesTextFieldTest/IntroductionTextFieldTestView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/LinesTextFieldTest/LetterTextFieldTestView.swift, Projects/Shared/DesignSystem/Sources/Components/TextField/LinesTextField/LinesTextField.swift, Projects/Shared/DesignSystem/Sources/Components/TextField/LinesTextField/TextFieldState.swift, Projects/Shared/DesignSystem/Sources/Extension/Text+Color.swift, Projects/Shared/DesignSystem/Sources/Extension/Text+Font.swift, Projects/Shared/DesignSystem/Sources/Extension/View+Extensions.swift, Projects/Shared/DesignSystem/Sources/Text/CustomStyleText.swift
이슈 #17 
https://github.com/user-attachments/assets/99fc42d6-d627-4e48-9f99-29f74ed23bff
- TextFieldState enum 구현
- TextFieldState에 따른 뷰 바인딩 구현
- Introduction, Letter TextField 구현
- 디자인 시스템에 컴포넌트들이 TextField로 정의되어있어서 TextEditor로 구현했지만 최대한 네이밍 TextField로했는데 오히려 별로면 수정할게!
- 일단 View에서는 최대한 비즈니스 로직들 빼고 나중에 사용하는 쪽에서 필요한 값들 전달할 수 있도록 구현했어 (TCA로 포커싱 & 비즈니스 로직관리할 수 있도록)
=> [Feature/#17] LinesTextField DesignSystem 구현

Projects/Domain/Auth/Interface/Sources/LoginManager/LoginManager.swift, Projects/Domain/Auth/Sources/LoginManager/LoginManager.swift, Projects/Domain/Profile/Interface/Sources/API/ProfileAPI.swift, Projects/Domain/Profile/Interface/Sources/DTO/Request/RegisteIntroductionRequestDTO.swift, Projects/Domain/Profile/Interface/Sources/DTO/Request/RegisterIntroductionRequestDTO.swift, Projects/Domain/Profile/Interface/Sources/DTO/Response/IntroductionExistResponseDTO.swift, Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileResponseDTO.swift, Projects/Domain/Profile/Interface/Sources/Entity/UserInterest.swift, Projects/Domain/Profile/Interface/Sources/Entity/UserProfile.swift, Projects/Domain/Profile/Interface/Sources/Entity/UserRegion.swift, Projects/Domain/Profile/Interface/Sources/ProfileClient.swift, Projects/Domain/Profile/Sources/ProfileClient.swift
이슈 #58 
- ProfileClient 프로필 조회 로직 구현
- ProfileClient 이미지 업로드 로직 구현
- ProfileClient 자기소개 등록 로직 구현
- ProfileClient 자기조개 작성 여부 로직 수정
ResponseDTO의 프로퍼리를 모두 옵셔널로 처리하는 것에 대한 고민
- 기존에는 서버의 ResponseData와 ResponseDTO의 옵셔널 여부로 인한 디코딩에러 발생시 error로 처리
- error로 처리해서 화면을 보여주지 않는 것보단 옵셔널로 처리해 화면을 보여주는 것이 사용자 경험 측면에서 좋다고 판단.
=> [Feature/#58] 프로필 만들기 Domain 구현

Plugins/DependencyPlugin/ProjectDescriptionHelpers/Project+Environment.swift
=> Setting/#64 App Store Connect 등록 준비

Projects/Feature/Sources/App/AppView.swift, Projects/Feature/Sources/TabView/MainTabView.swift
- App View WithPerceptionTracking 처리
- Main Tab View store @Perception.Bindable 처리
=> Fix/#70 App View WithPerceptionTracking 처리

Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/UserProfileTest/UserProfileTestView.swift, Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_verticalLine.imageset/Contents.json, Projects/Shared/DesignSystem/Resources/Images.xcassets/icon_verticalLine.imageset/icon_verticalLine.svg, Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift, Projects/Shared/DesignSystem/Sources/Image/BottleImageSystem+Icon.swift
이슈 #78 
https://github.com/user-attachments/assets/863b13da-a6f3-41d7-90bf-95ef49783e65
- UserProfileView 구현
=> [Feature/#78] 사용자 프로필 DesignSystem 구현

Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/StopCardTest/StopCardTestView.swift, Projects/Shared/DesignSystem/Sources/Components/Card/Stop/StopCardView.swift
이슈 #80 
https://github.com/user-attachments/assets/4fbd69bb-e936-44af-854a-96fd16d34bab
- StopCardView 구현
=> [Feature/#80] 대화 중단 Card DesignSystem 구현

Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift, Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift, Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachView.swift, Projects/Feature/SandBeach/Interface/Sources/SandBeach/UserStateType.swift, Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButton.swift, Projects/Shared/DesignSystem/Sources/Components/Button/SolidButton/SolidButtonStyle.swift, Projects/Shared/DesignSystem/Sources/Components/Popup/PopupView.swift, Projects/Shared/DesignSystem/Sources/Components/Popup/TriangleView.swift, Projects/Shared/DesignSystem/Sources/Extension/View+Extensions.swift, Projects/Shared/DesignSystem/Sources/Padding/BottlePaddingType.swift, Projects/Shared/DesignSystem/Sources/Radius/BottleRadiusType.swift
이슈 #92 
https://github.com/user-attachments/assets/55471364-022b-4e1e-b9b2-2610c327039a
- 모래사장 일러스트 이미지 적용
- 추가적으로 유저 상태가 추가돼서 로직 변경했음!
=> [Feature/#92] 모래사장 화면 일러스트이미지 작업

Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupFeature.swift, Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift, Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadFeature.swift, Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift, Projects/Feature/SandBeach/Project.swift, Projects/Shared/DesignSystem/Sources/Modifiers/NavigationBarModifier.swift
이슈 #106 
- NavigationBar Modifier 구현
- NavigationBar Modifier 적용
- 일단 뒤로가기랑 신고하기 버튼 두 개 Modifier로 NavigationBar 세팅할 수 있게 구현해뒀음! 네이밍 괜찮은지 체크 좀!
=> [Feature/#106] navigationbar 커스텀

Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupFeature.swift, Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupView.swift, Projects/Shared/DesignSystem/Sources/Components/TextField/LinesTextField/LinesTextField.swift
이슈 #94 
- 글자수 제한 기능 추가
- 추가적으로 테스트하다가 발견한 화면 클릭 시 placeHolder 없어지던 버그 수정
=> [feature#94] TextEditor 글자수 제한 기능 추가

Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift, Projects/Domain/Report/Interface/Sources/API/ReportAPI.swift, Projects/Domain/Report/Interface/Sources/DTO/Request/ReportUserRequestDTO.swift, Projects/Domain/Report/Interface/Sources/Entity/UserReportInfo.swift, Projects/Domain/Report/Interface/Sources/ReportClient.swift, Projects/Domain/Report/Interface/Sources/ReportInterface.swift, Projects/Domain/Report/Project.swift, Projects/Domain/Report/Sources/ReportClient.swift, Projects/Domain/Report/Sources/Source.swift, Projects/Domain/Report/Testing/Sources/ReportTesting.swift, Projects/Domain/Report/Tests/Sources/ReportTest.swift, Projects/Feature/Report/Example/Sources/AppView.swift, Projects/Feature/Report/Interface/Sources/ReportUserFeature.swift, Projects/Feature/Report/Interface/Sources/ReportUserFeatureInterface.swift, Projects/Feature/Report/Interface/Sources/ReportUserView.swift, Projects/Feature/Report/Interface/Sources/UserReportProfile.swift, Projects/Feature/Report/Project.swift, Projects/Feature/Report/Sources/Source.swift, Projects/Feature/Report/Testing/Sources/ReportTesting.swift, Projects/Feature/Report/Tests/Sources/ReportTest.swift, Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift, Projects/Shared/DesignSystem/Sources/Components/TextField/LineTextField/LineTextField.swift, Projects/Shared/DesignSystem/Sources/Modifiers/EndEditingModifier.swift
이슈 #112 
https://github.com/user-attachments/assets/b75dd948-98d6-48fc-82d5-45f5bb4651e9
- LineTextField 디자인 시스템 추가
- UserReport Feature 모듈 추가
- UserReportView 구현
- UserReportFeature 구현
- Report Domain 모듈 추가
- ReportClient 구현
신고 완료됐을 때 action 핸들링은 사용하는 쪽에서 delegate로 처리할 수있게 delegate action으로 처리했음!
=> [Feature/#112] 신고하기 화면 및 기능 구현

Projects/Domain/Bottle/Interface/Sources/API/BottleAPI.swift, Projects/Domain/Bottle/Interface/Sources/BottleClient.swift, Projects/Domain/Bottle/Interface/Sources/DTO/Request/BottleImageShareRequestDTO.swift, Projects/Domain/Bottle/Interface/Sources/DTO/Request/FinalSelectRequestDTO.swift, Projects/Domain/Bottle/Interface/Sources/DTO/Request/RegisterLetterAnswerRequestDTO.swift, Projects/Domain/Bottle/Sources/BottleClient.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/QuestionPingPongView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/Sources/App/AppFeature.swift, Projects/Shared/DesignSystem/Sources/Components/Card/Stop/StopCardView.swift
=> [Feature/#122] 보틀 보관함 가치관 문답 탭 구현

Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift, Projects/Domain/WebView/Sources/WebViewClient.swift, Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpFeature.swift, Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpFeatureInterface.swift, Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpView.swift, Projects/Feature/GeneralSignUp/Interface/Sources/TermsWebView.swift
이슈: #116
- 일반 회원 가입 약관 연결 웹뷰 이벤트 핸들링 추가
=> [feature/#116] 일반 회원 가입 약관 연결 웹뷰 이벤트 핸들링 추가

Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift, Projects/Feature/Report/Interface/Sources/ReportUserFeature.swift, Projects/Feature/Report/Interface/Sources/ReportUserFeatureInterface.swift
=> [feature/#127] BottleStorage ReportFeature 연결

Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift, Projects/Shared/DesignSystem/Sources/Extension/UIImage+Extensions.swift
이슈 #111 
- 1MB 이하로 이미지 다운 샘플링 구현
- 임시로 구현된 다운 샘플링이라 추가 작업 필요
=> [feature#111] 이미지 다운샘플링 구현

Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift, Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_clearDelete.imageset/Contents.json, Projects/Shared/DesignSystem/Resources/Images.xcassets/icon/icon_plus.imageset/Contents.json, Projects/Shared/DesignSystem/Sources/Components/ETC/ImagePickerButton.swift, Projects/Shared/DesignSystem/Sources/Components/ImageView/RemoteImageView.swift
이슈 #134 
- RemoteImageView scaledToFill() 처리
- 이미지 선택 버튼 이미지 UIImage 사이즈를 통한 비율 수정
=> [feature#134] 프로필 이미지 비율 수정

Projects/Domain/Auth/Interface/Sources/DTO/Response/SignInResponseDTO.swift
이슈 #135 
- SignInResponseDTO의 자기소개 여부 key값으로 처리하던 것 DTO 수정
=> [feature/#135] 로그인 시 프로필 등록여부 확인 로직 수정

Projects/Domain/Bottle/Interface/Sources/BottleClient.swift, Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottleListResponseDTO.swift, Projects/Domain/Bottle/Interface/Sources/Entity/UserBottleInfo.swift, Projects/Domain/Bottle/Sources/BottleClient.swift, Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift, Projects/Feature/SandBeach/Interface/Sources/SandBeach/UserStateType.swift, Projects/Shared/Util/Interface/Sources/Date+Extensions.swift
이슈 #138 
- BottleListResponseDTO 수정
- UserBottle Entity 추가
- 서버에서 받은 시간으로 새로은 보틀 도착 표시되도록 수정.
=> [Feature/#138] 모래사장화면 새로운 보틀 도착 시간표시 구현

Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileResponseDTO.swift, Projects/Domain/Profile/Interface/Sources/Entity/UserProfile.swift, Projects/Domain/Profile/Interface/Sources/ProfileClient.swift, Projects/Domain/Profile/Sources/ProfileClient.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Feature/ProfileSetup/Interface/Sources/IntroductionSetup/IntroductionSetupFeature.swift, Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift, Projects/Feature/Sources/TabView/MainTabViewFeature.swift, Projects/Feature/TabBar/Interface/Sources/TabBarModifier.swift, Projects/Shared/DesignSystem/Sources/Components/Card/Letter/LettetCardView.swift
이슈 #143
- 마이페이지 구현
- UserProfile -> ProfileSelect로 변경
=> [Feature#143] 웹뷰 이슈로 인한 마이페이지 구현

Projects/Domain/Bottle/Interface/Sources/DTO/Request/FinalSelectRequestDTO.swift, Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottlePingPongResponseDTO.swift, Projects/Domain/Bottle/Interface/Sources/Entity/BottlePingPong.swift, Projects/Domain/Bottle/Sources/BottleClient.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/FinalSelectPingPongView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PhotoSharePingPongView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/QuestionAndAnswer/QuestionAndAnswerView.swift
=> [Feature/#141] 보틀 가치관 문답 상태관리 개선

Projects/Domain/Bottle/Interface/Sources/DTO/Response/BottlePingPongResponseDTO.swift, Projects/Domain/Bottle/Interface/Sources/Entity/BottlePingPong.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Matching/MatchingView.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
- 매칭화면 장소 추천 기능 추가
- BottlePingPongResponseDTO 에 meetingPlace, meetingPlaceImageUrl 파라미터 추가
=> [feature/#151] 매칭화면 장소 추천 기능 추가

Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift, Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift, Projects/Shared/DesignSystem/Sources/Components/ImageView/BlurImageView.swift, Projects/Shared/DesignSystem/Sources/Components/ListItem/BottleStorageItem.swift
- 디자인 시스템에 blur image view 구현
- 핑퐁 리스트, 핑퐁 상세 화면 blur image view 적용
=> [Feature/#156] blur profile image view 구현

Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootFeature.swift, Projects/Feature/SandBeach/Interface/Sources/Root/SandBeachRootView.swift
이슈 #167 
- 자기소개 등록 indicator 추가
=> [feature/167] 자기소개 등록 indicator 추가

Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/Sources/App/AppFeature.swift
이슈 #176 
- AppFeature - LoginCheckCompleted Action Error 처리
빨리 도메인 에러 작업 들어가야할듯..ㅋㅋ
=> [Feature/#176] 유효하지 않은 토큰으로 로그인 시 에러 처리

Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift, Projects/Feature/Report/Interface/Sources/ReportUserView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/UserProfileTest/UserProfileTestView.swift, Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift
- 이슈: #174 
- 프로필 이미지 blur 처리 적용
=> [Feature/#147] 프로필 이미지 blur 처리 적용

Projects/Feature/ProfileSetup/Interface/Sources/ProfileImageUpload/ProfileImageUploadView.swift
이슈 #187 
- 이미지 선택시 PhotosPickerItem 삭제
=> [Feature/#187] 이미지 선택시 PhotosPickerItem 삭제

Projects/Domain/Bottle/Interface/Sources/API/BottleAPI.swift, Projects/Domain/Bottle/Interface/Sources/BottleClient.swift, Projects/Domain/Bottle/Interface/Sources/Entity/BottleStorageList.swift, Projects/Domain/Bottle/Sources/BottleClient.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageFeatureInterface.swift, Projects/Feature/BottleStorage/Interface/Sources/BottleStorage/BottleStorageView.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeature.swift, Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PingPongDetail/PingPongDetailFeatureInterface.swift
- 핑퐁 detail 화면 진입시 isRead값 false 인 경우 핑퐁 조회 API 요청 처리
=> [Feature/#188] 핑퐁 조회 API 연결

Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
=> v1.0.1 Release -> Develop

Projects/Feature/Login/Interface/Sources/Login/AppleLoginFeature.swift, Projects/Feature/Login/Interface/Sources/Login/AppleLoginFeatureInterface.swift, Projects/Feature/Login/Interface/Sources/Login/AppleLoginView.swift, Projects/Feature/Login/Interface/Sources/Login/LoginFeature.swift, Projects/Feature/Login/Interface/Sources/Login/LoginFeatureInterface.swift, Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
=> [Feature/#194] 애플 로그인 sns 버튼 클릭시 보이도록 수정

Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
=> v1.0.2 Release -> Develop

Projects/App/Sources/AppDelegate.swift, Projects/Domain/Auth/Sources/AuthClient.swift, Projects/Domain/User/Interface/Sources/UserClient.swift, Projects/Domain/User/Sources/UserClient.swift, Projects/Feature/Sources/App/AppDelegateFeature.swift, Projects/Feature/Sources/App/AppFeature.swift
이슈 #204 
- FCM Token UserClient로 관리
- FCM Token Recevied 된 후 LoginView 보이도록 수정
=> [Feature/#204] 카카오로그인 충돌

Projects/Domain/Auth/Sources/LoginManager/LoginManager.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
=> v1.0.5 Release -> Main

Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/PhotoSharePingPongView.swift
이슈 #207 
- PeerProfileImage, MyProfileImage clipped() 메소드 추가
=> [Feature/#207] 사진 공개 프로필 이미지 비율 수정

Projects/Shared/DesignSystem/Sources/Modifiers/AsThrottleButtonModifier.swift
이슈 #211 
- AsThrottleButtonModifier 내부 Throttling 구현
=> [feature#221] 버튼 throttling 처리

README.md
이슈 #237 
- README 작성
- 간단하게 README 작성해봤는데 추가할거나 수정할 거 있으면 말해줘!
=> [Docs#237] README 작성

Projects/Feature/SandBeach/Interface/Sources/SandBeach/SandBeachFeatureInterface.swift, Projects/Feature/Sources/SplashView/SplashFeature.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
=> release/1.0.7 -> develop

Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/ListTest/ListTestView.swift, Projects/Shared/DesignSystem/Sources/Components/List/ArrowListView.swift, Projects/Shared/DesignSystem/Sources/Components/List/ButtonListView.swift, Projects/Shared/DesignSystem/Sources/Components/List/ListContainerView.swift, Projects/Shared/DesignSystem/Sources/Components/List/TextListView.swift, Projects/Shared/DesignSystem/Sources/Components/List/ToggleListView.swift, Projects/Shared/DesignSystem/Sources/Components/Toggle/BottleToggle.swift
이슈 #224 
https://github.com/user-attachments/assets/5302e472-dfbd-4aee-b429-e6c6c49b1290
- ArrowListView 구현
- ToggleListView 구현
- ButtonListView 구현
- 기본으로 제공하는 Toggle의 TintColor만 변경해서 사용하려고 했으나 
높이와 너비를 바꾸기 위해 ToggleStyle 프로토콜을 통해서 BottleToggleStyle, BottleToggle 구현
=> [Feature/#224] lists design system

Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift
=> [Feature/#225] 마이페이지 리뉴얼 작업

Projects/Domain/Profile/Interface/Sources/API/ProfileAPI.swift, Projects/Domain/Profile/Interface/Sources/DTO/Request/MatchingActivateRequestDTO.swift, Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileResponseDTO.swift, Projects/Domain/Profile/Interface/Sources/ProfileClient.swift, Projects/Domain/Profile/Sources/ProfileClient.swift, Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingFeature.swift, Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/AccountSetting/AccountSettingView.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift
이슈 #254 
https://github.com/user-attachments/assets/457689d9-f62d-4ff8-b65a-20afe390177c
- 마이페이지 계정 관리 View, 기능 구현
=> [Feature/#254] 마이페이지 계정 관리 구현

Projects/Core/Network/Project.swift, Projects/Domain/User/Interface/Sources/API/UserAPI.swift, Projects/Domain/User/Interface/Sources/DTO/Request/BlockContactRequestDTO.swift, Projects/Domain/User/Interface/Sources/UserClient.swift, Projects/Domain/User/Interface/Sources/UserError.swift, Projects/Domain/User/Sources/UserClient.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Shared/DesignSystemThirdPartyLib/Project.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
> 이슈: #251 
- 연락처 업데이트 성공
https://github.com/user-attachments/assets/58e84364-1599-456f-a5e4-d7ff7ecbb1cd
- 연락처 접근 권한 거부
https://github.com/user-attachments/assets/df93ec99-7ad0-4a98-9437-891094419742
- 연락처 차단 기능 구현
- User Error 는 DomainUser 모듈에 만들어 놓았어!
=> [Feature/#251] 연락처 차단 기능 구현

Projects/Core/URLHandler/Interface/Sources/BottleURLType.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
이슈 #259 
- infoPlist 카카오톡 채널 톡 URL 추가
- 1:1 문의 클릭 시 카카오톡 채널 톡으로 이동
=> [Feature/#259] 마이페이지 1:1 문의 기능 구현

Plugins/DependencyPlugin/ProjectDescriptionHelpers/Modules.swift, Projects/Core/URLHandler/Interface/Sources/BottleURLType.swift, Projects/Domain/Application/Interface/Sources/ApplicationClient.swift, Projects/Domain/Application/Project.swift, Projects/Domain/Application/Sources/ApplicationClient.swift, Projects/Domain/Application/Testing/Sources/ApplicationTesting.swift, Projects/Domain/Application/Tests/Sources/ApplicationTest.swift, Projects/Domain/User/Sources/UserClient.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Shared/DesignSystem/Sources/Components/List/ButtonListView.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
> 이슈: #257 
- DomainApplication module 생성 해서 버전관련 로직 작성
- ButtonListView에서 업데이트 버튼 보여지는 여부 설정이 필요해서 isShowButton 프로퍼티 도입
- 지금 시뮬레이터에서 빌드는 잘 되는데 실기기에서 빌드가 안되서 혹시 실기기에서 빌드 잘 되는지 확인 한번만 부탁해!
=> [Feature/#257] 마이페이지 앱 버전 업데이트 기능 구현

Projects/Feature/BaseWebView/Interface/Sources/BaseWebView.swift, Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift, Projects/Feature/MyPage/Example/Sources/AppView.swift, Projects/Feature/MyPage/Interface/Sources/EditProfile/EditProfileFeature.swift, Projects/Feature/MyPage/Interface/Sources/EditProfile/EditProfileFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/EditProfile/ProfileEditView.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageView.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootFeatureInterface.swift, Projects/Feature/MyPage/Interface/Sources/MyPageRootView.swift, Projects/Feature/MyPage/Project.swift
> #264 
- 마이페이지 프로필 수정 웹뷰 연결
- BaseWebViewType에서 rawValue를 사용해서 path를 명시해줬었는데 path 연산 프로퍼티 만들어서 명확하게 어떤거 나타내는지 명시해줬어!
=> [feature/#264] 마이페이지 프로필 수정 웹뷰 연결

Projects/Core/URLHandler/Interface/Sources/BottleURLType.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeatureInterface.swift
이슈 #263 
- BottleURLType 설정 URLScheme 추가
- 연락처 접근 권한 미허용시 설정으로 이동
=> [Feature/#263] 연락처 접근 권한 허용안함 시 설정 이동

Projects/Domain/Profile/Interface/Sources/DTO/Response/ProfileResponseDTO.swift, Projects/Feature/MyPage/Interface/Sources/MyPage/MyPageFeature.swift
이슈 #266 
- UserInfo blockedContactsCount 추가
- 마이페이지 onLoad시 차단된 전화번호수 동기화
=> [Feature/#266] 마이페이지 진입 시 연락처 차단 개수 동기화

Projects/Feature/BottleArrival/Interface/Sources/BottleArrivalView.swift, Projects/Feature/GeneralSignUp/Interface/Sources/GeneralSignUpView.swift, Projects/Feature/Login/Interface/Sources/GeneralLogIn/GeneralLogInView.swift, Projects/Feature/MyPage/Interface/Sources/EditProfile/ProfileEditView.swift, Projects/Feature/Onboarding/Interface/Sources/Onboarding/OnboardingView.swift
> 이슈: #278 
- 웹뷰들 상단 safe area 무시하도록 수정
=> [Feature/#278] 웹뷰 상단 safe area 무시하도록 수정

Projects/Feature/Login/Interface/Sources/Login/AppleLoginView.swift, Projects/Feature/Login/Interface/Sources/Login/LoginView.swift
> 이슈: #282 
- 로그인 화면 로그인 버튼 vstack 하단 마진 수정
=> [Fix/#282] 로그인 화면 로그인 버튼 vstack 하단 마진 수정

Projects/Core/Logger/Interface/Sources/Log.swift, Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
> 이슈: #303 
- assertion error 슬랙 로깅 연결
=> [Setting/#303] assertion error 슬랙 로깅 연결

Projects/Feature/Guide/Interface/Sources/StartGuide/StartGuideView.swift
> 이슈: #308 
- 이미지 마진 값 수정
- CTA 버튼 이름 수정
=> [Fix/#308] onboarding 4 디자인 qa 반영

Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift
> 이슈: #296 
- 웹뷰 프로필 생성 변경된 URL 적용
=> [Refactor/#296] 웹뷰 프로필 생성 변경된 URL 적용

Projects/Core/WebView/Interface/Sources/BottleWebViewAction.swift, Projects/Domain/WebView/Sources/WebViewClient.swift, Projects/Feature/BaseWebView/Interface/Sources/BaseWebViewType.swift, Projects/Feature/GoodFeeling/Interface/Sources/GoodFeeling/GoodFeelingFeatureInterface.swift, Projects/Feature/GoodFeeling/Interface/Sources/GoodFeeling/GoodFeelingView.swift, Projects/Feature/GoodFeeling/Interface/Sources/Root/FeatureGoodFeelingRootView.swift, Projects/Feature/GoodFeeling/Interface/Sources/Root/GoodFeelingRootFeature.swift, Projects/Feature/GoodFeeling/Interface/Sources/Root/GoodFeelingRootFeatureInterface.swift, Projects/Feature/GoodFeeling/Interface/Sources/SentBottleDetail/SentBottleDetailFeature.swift, Projects/Feature/GoodFeeling/Interface/Sources/SentBottleDetail/SentBottleDetailFeatureInterface.swift, Projects/Feature/GoodFeeling/Interface/Sources/SentBottleDetail/SentBottleDetailView.swift
> 이슈: #306 
- 호감 리스트 -> 호감 상세 화면 이동 여결
- 떠내려보내기 이벤트 연결
- 문답 시작하기 이벤트 연결
- 백버튼 이벤트 연결
=> [Feature/#306] 호감 tab 웹뷰 action 핸들링

Projects/Feature/BottleStorage/Interface/Sources/PingPongDetail/View/SubViews/Introduction/IntroductionView.swift, Projects/Feature/Report/Interface/Sources/ReportUserView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/UserProfileTest/UserProfileTestView.swift, Projects/Shared/DesignSystem/Sources/Components/Card/UserProfile/UserProfileView.swift, Projects/Shared/DesignSystem/Sources/Components/ListItem/BottleStorageItem.swift
> 이슈: #319 
- 프로필 이미지 블러 처리 로직 제거
=> [Refactor/#319] 프로필 이미지 블러 처리 로직 제거

Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
=> Release/1.0.9 -> develop

Projects/Shared/DesignSystem/Example/Sources/DesignSystemExampleView/DesignSystemExampleView.swift, Projects/Shared/DesignSystem/Example/Sources/SubViews/BottleStorageList.swift, Projects/Shared/DesignSystem/Sources/Components/Card/PingPong/PingPongUserView.swift
이슈 #290 
https://github.com/user-attachments/assets/6ec71559-e12a-414c-9450-5ad67278ee7e
- PingPoingUserView 구현
- PingPoingUserView 디자인 시스템 데모 앱 추가
기존 BottleStoargeItem(기존 View) 내부에서 작업안하고 새로운 View 만들어서 작업했어!
다음에 기존 Feature에 View랑 기능 넣을 때 BottleStoargeItem 삭제하는거로 진행할게!
=> [Feature/#290] 문답화면 리스트 디자인시스템 구현
